#!/bin/bash
# COLOR
COff='\033[0m'       # Text Reset
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

a=1
b=2
c=3
d=4
e=5
f=6
g=7
h=8
i=9
j=10
k=11
l=12
m=13
n=14
o=15
p=16
q=17
r=18
s=19
t=20
u=21
v=22
w=23
x=24
y=25
z=26
echo -e "${BGreen}[1].gf"
echo -e "${BGreen}[2].gf-patterns"
echo -e "${BGreen}[3].html-tool"
echo -e "${BGreen}[4].censys"
echo -e "${BGreen}[5].httprobe"
echo -e "${BGreen}[6].certspotter"
echo -e "${BGreen}[7].waybackurls"
echo -e "${BGreen}[8].anew"
echo -e "${BGreen}[9].fff"
echo -e "${BGreen}[10].meg"
echo -e "${BGreen}[11].comb"
echo -e "${BGreen}[12].subfinder"
echo -e "${BGreen}[13].assetfinder"
echo -e "${BGreen}[14].dalfox"
echo -e "${BGreen}[15].tok"
echo -e "${BGreen}[16].jq"
echo -e "${BGreen}[17].httpx"
echo -e "${BGreen}[18]."
echo -e "${BGreen}[19]."
echo -e "${BGreen}[20]."

if [ $a == $pilih  ];then
	echo -e"${BRed}▶Installing gf"
	go install -v github.com/tomnomnom/gf@latest
	echo -e "${BGreen}▶success"
elif [ $b == $pilih  ];then
	echo -e"${BRed}▶Installing gf-patterns"
	git clone https://github.com/cryonayes/GF-Patterns
	mkdir ~/.gf
	cp GF-Patterns/*.json ~/.gf
        echo -e "${BGreen}▶success"
elif [ $c == $pilih  ];then
	echo -e"${BRed}▶Installing html-tool"
	go install -v github.com/tomnomnom/hacks/html-tool@latest
        echo -e "${BGreen}▶success"
elif [ $d == $pilih  ];then
	echo -e"${BRed}▶Installing censys"
	apt install censys
        echo -e "${BGreen}▶success"
elif [ $e == $pilih  ];then
        echo -e"${BRed}▶Installing httprobe"
	go install github.com/tomnomnom/httprobe@latest
        echo -e "${BGreen}▶success"
elif [ $f == $pilih  ];then
        echo -e"${BRed}▶Installing certspotter"
	go install software.sslmate.com/src/certspotter/cmd/certspotter@latest
        echo -e "${BGreen}▶success"
elif [ $g == $pilih  ];then
        echo -e"${BRed}▶Installing waybackurls"
	go install github.com/tomnomnom/waybackurls@latest
        echo -e "${BGreen}▶success"
elif [ $h == $pilih  ];then
        echo -e"${BRed}▶Installing anew"
	go install -v github.com/tomnomnom/anew@latest
        echo -e "${BGreen}▶success"
elif [ $i == $pilih  ];then
        echo -e"${BRed}▶Installing fff"
	go install -v  github.com/tomnomnom/fff@latest
        echo -e "${BGreen}▶success"
elif [ $j == $pilih  ];then
        echo -e"${BRed}▶Installing meg"
	go install -v  github.com/tomnomnom/meg@latest
        echo -e "${BGreen}▶success"
elif [ $k == $pilih  ];then
        echo -e"${BRed}▶Installing comb"
	go install -v  github.com/tomnomnom/comb@latest
        echo -e "${BGreen}▶success"
elif [ $l == $pilih  ];then
        echo -e"${BRed}▶Installing subfinder"
	go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        echo -e "${BGreen}▶success"
elif [ $m == $pilih  ];then
        echo -e"${BRed}▶Installing assetfinder"
	
        echo -e "${BGreen}▶success"
elif [ $n == $pilih  ];then
        echo -e"${BRed}▶Installing dalfox"
	go install -v  github.com/hahwul/dalfox/v2@latest
        echo -e "${BGreen}▶success"
elif [ $o == $pilih  ];then
        echo -e"${BRed}▶Installing tok"
	go install -v github.com/tomnomnom/hacks/tok@latest
        echo -e "${BGreen}▶success"
elif [ $p == $pilih  ];then
        echo -e"${BRed}▶Installing jq"
	apt install jq
        echo -e "${BGreen}▶success"
elif [ $q == $pilih  ];then
        echo -e"${BRed}▶Installing httpx"
	go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
        echo -e "${BGreen}▶success"
elif [ $r == $pilih  ];then
        echo -e"${BRed}▶Installing "
	
        echo -e "${BGreen}▶success"
elif [ $s == $pilih  ];then
        echo -e"${BRed}▶Installing "
	
        echo -e "${BGreen}▶success"
elif [ $t == $pilih  ];then
        echo -e"${BRed}▶Installing "
	
        echo -e "${BGreen}▶success"
elif [ $u == $pilih  ];then
        echo -e"${BRed}▶Installing "
	
        echo -e "${BGreen}▶success"


fi
cp  ~/go/bin/* /usr/local/bin
echo -e "${BRed}▶copy file success"
